# Generated by Django 5.1.2 on 2024-11-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profilemodel_type_of_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="available_words",
            field=models.IntegerField(default=5000),
        ),
    ]
