# Generated by Django 5.1.2 on 2024-11-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_profilemodel_available_words"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="available_words",
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
