# Generated by Django 5.1.2 on 2024-12-04 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_email_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profilemodel",
            options={"verbose_name": "profile", "verbose_name_plural": "profiles"},
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="available_words",
            field=models.PositiveIntegerField(
                default=5000, verbose_name="available words"
            ),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="type_of_plan",
            field=models.CharField(
                choices=[("Free", "Free"), ("Premium", "Premium")],
                default="Free",
                max_length=10,
                verbose_name="type of plan",
            ),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
