# Generated by Django 5.1.2 on 2024-12-06 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_content_artices_model_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="content_artices_model",
            name="content",
            field=models.TextField(verbose_name="content"),
        ),
        migrations.AlterField(
            model_name="content_artices_model",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="content_artices_model",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="articles/images", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="content_artices_model",
            name="title",
            field=models.CharField(max_length=500, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="content_artices_model",
            name="type",
            field=models.CharField(
                choices=[
                    ("Blog content", "Blog content"),
                    ("Content write", "Content write"),
                    ("News content", "News content"),
                    ("Scientific content", "Scientific content"),
                    ("Educational content", "Educational content"),
                    ("Other", "Other"),
                ],
                max_length=50,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="content_artices_model",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="humanized_texts_model",
            name="humanized_text",
            field=models.TextField(verbose_name="humanized text"),
        ),
        migrations.AlterField(
            model_name="humanized_texts_model",
            name="original_text",
            field=models.TextField(verbose_name="original text"),
        ),
        migrations.AlterField(
            model_name="saved_documents",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="saved_documents",
            name="number_of_words",
            field=models.PositiveBigIntegerField(verbose_name="number of words"),
        ),
        migrations.AlterField(
            model_name="saved_documents",
            name="purpose",
            field=models.CharField(max_length=500, verbose_name="purpose"),
        ),
        migrations.AlterField(
            model_name="saved_documents",
            name="text",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.humanized_texts_model",
                verbose_name="text",
            ),
        ),
        migrations.AlterField(
            model_name="saved_documents",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
