# Generated by Django 5.1.2 on 2024-12-06 06:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_content_artices_model_content_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Billing_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(auto_now_add=True, verbose_name="paid date"),
                ),
                (
                    "expire_date",
                    models.DateField(blank=True, null=True, verbose_name="expire date"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Monthly", "Monthly"), ("Yearly", "Yearly")],
                        max_length=20,
                        verbose_name="type",
                    ),
                ),
                (
                    "how_much",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ],
                        verbose_name="how much",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "billing",
                "verbose_name_plural": "billings",
                "db_table": "billings",
            },
        ),
    ]
