# Generated by Django 5.1.2 on 2024-11-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=100)),
                ("answer", models.TextField()),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "db_table": "faqs",
            },
        ),
    ]
