# Generated by Django 5.1.2 on 2024-12-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainPage", "0002_faqsmodel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmodel",
            options={"verbose_name": "contact", "verbose_name_plural": "contacts"},
        ),
        migrations.AlterField(
            model_name="contactmodel",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="contactmodel",
            name="message",
            field=models.TextField(verbose_name="message"),
        ),
        migrations.AlterField(
            model_name="contactmodel",
            name="name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="faqsmodel",
            name="answer",
            field=models.TextField(verbose_name="answer"),
        ),
        migrations.AlterField(
            model_name="faqsmodel",
            name="question",
            field=models.CharField(max_length=100, verbose_name="question"),
        ),
    ]
